version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - static:/static
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=studentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Vrushabh_123
    volumes:
      - pgdata:/var/lib/postgress/data

  nginx:
    build: ./nginx
    container_name: server
    restart: always
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - web
      
volumes:
  static:
  pgdata:
